version: "3"
services:
  postgres:
    image: "postgres:11"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "214470"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
