version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: 214470
      DB_DATABASE: "taskmanagement"
    ports:
      - 5000:5000

  postgres:
    image: "postgres:11"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "214470"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
